server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Proxy auth calls a Floci Cognito (desde el pod, floci es accesible por nombre en floci-net)
    location /cognito/ {
        proxy_pass http://floci:4566/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy API calls directamente al servicio k8s (evita LocalStack API GW)
    location /restapis/787044f267/local/_user_request_/ {
        proxy_pass http://tasks-creator:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
