spring:
  r2dbc:
    url: ${R2DBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  port: ${SERVER_PORT:8081}

aws:
  endpoint-url: ${AWS_ENDPOINT_URL:http://localhost:4566}
  region: ${AWS_REGION:us-east-1}
  access-key: ${AWS_ACCESS_KEY_ID:test}
  secret-key: ${AWS_SECRET_ACCESS_KEY:test}

sqs:
  queue-url: ${SQS_QUEUE_URL}
